### ISSUE TITLE
Doesn't work with prebuilt images

### ISSUE THREAD

**Issue by Jeremygu** [Digilent/Petalinux-Zybo-Z7-20#4]
After I boot the zybo-z7-20 using the pre-built images, it gets stuck before appearing root login.

I copied BOOT.BIN and image.ub to my SD-card (also set the board to boot in SDcard mode).
`../Zybo-Z7-20$ cp pre-built/linux/images/BOOT.BIN /media/jeremy/B899-DF18/`
`../Zybo-Z7-20$ cp pre-built/linux/images/image.ub /media/jeremy/B899-DF18/`

Some outputs of minicom on my PC are as following.

....
Starting system message bus: dbus.
Starting Dropbear SSH server: Generating key, this may take a while...
Public key portion is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcy2yUmPIMJYLoIguDRV/djK/iUiy7w0MYE6DphLLg/YStVolLy0De2TweXXXDMUiCRctoSdHbsYljFQqVfOUZRRQW++tjuXOe0
Fingerprint: md5 78:8b:83:e0:15:d2:d9:0d:45:0d:28:8e:d1:2f:b9:a9
dropbear.
hwclock: can't open '/dev/misc/rtc': No such file or directory
Starting syslogd/klogd: done
Starting tcf-agent: OK

It just stopped here. 
I've attached the whole outputs.

[output on UART terminal after Booting from pre-built images.docx](https://github.com/Digilent/Petalinux-Zybo-Z7-20/files/2767448/output.on.UART.terminal.after.Booting.from.pre-built.images.docx)

Any points would be appreciated.

**Comment by Jeremygu** [comment]
I figured it out using SDK terminal in XSDK although there appear some strange characters, like `7[r[999;999H[6nroot@Zybo-Z7-20:~# `.

Just for anyone in the same situation, change to use another UART terminal () and try again. I have no idea why my minicom 2.7 (on Ubuntu16.04LTS) cannot present the last several lines.

**Comment by fangzr** [comment]
You can see here.
Please make sure that Minicom Ctrl-A -> O -> Serial Port Setup -> Hardware flow control->No,
and make Ctrl-A -> Z -> E

**Comment by zegonix** [comment]
Thanks so much, I had no idea where to look to solve my problem!
